### ISSUE TITLE
Question: Forwarding slave to another with different indices

### ISSUE THREAD

**Issue by Gert-dev** [tiagocoutinho/modbus-proxy#25]
Hi

I'm wondering if it is possible to forward one slave index to another, or - in other words - to change its index? For example: ModBus server foo.com:502 has a slave on index 0, and I would like to proxy it, but forward slave **1** to foo.com:502 slave **0** instead of 0 to 0 or 1 to 1.

The reason I'm asking this is because some MODBUS/TCP servers, such as the Huawei SUN-2000L, have their slave on index 0, which - if I understood correctly - is not meant to be used as _actual_ slave index. As a result, some software (e.g. Loxone's MODBUS support) refuses to read from it and requires a minimum slave index of 1. Meanwhile, tools such as qModMaster work fine with slave index 0 to read the necessary data. Having this support would allow me to work around this problem with quirky MODBUS implementations, and link both.

Thanks!

**Comment by tiagocoutinho** [comment]
Hi,
So far we only support [modbus TCP protocol](https://en.wikipedia.org/wiki/Modbus#Modbus_TCP_frame_format). So when you say "slave index" are you talking about the "Unit identifier" ?

Assuming you are the answer is no. We do not tampering with any part of the Modbus TCP frame.

I do think it is an interesting feature so if anyone is willing it I would be honored to code review a PR.

**Comment by Gert-dev** [comment]
> So far we only support [modbus TCP protocol](https://en.wikipedia.org/wiki/Modbus#Modbus_TCP_frame_format). So when you say "slave index" are you talking about the "Unit identifier" ?

Yes, I think that is indeed it, e.g. what is `253` here:

![image](https://user-images.githubusercontent.com/24809863/215318607-91457e8d-205e-4866-a5a8-2c5cf37f11a3.png)

(I got confused because there seems to be a bug on qModMaster where if you had it on "TCP" before, on startup it will still say "Slave Address" as is the case for RTU; it fixes itself when you go back and forth.)

> I do think it is an interesting feature so if anyone is willing it I would be honored to code review a PR.

:+1: I can't make any promises, but I might take a whack at this at some point. I'm also investigating alternative solutions simultaneously (i.e. getting Loxone/Huawei to fix their stuff in my case), but I'm pessimistic either will do so.
