### ISSUE TITLE
RPi Hass Core Docker

### ISSUE THREAD

**Issue by EvoSems** [tiagocoutinho/modbus-proxy#35]
Hi. trying to install a docker to my Rpi4 to access my inverter for Homeassistant. Core Version. (No Add-ons)

if using for example.

docker run -p 5020:502 -v $PWD/conf.yml:/src/conf.yml modbus-proxy -c /src/conf.yml

I get back

`$ docker run -p 5020:502 -v $PWD/conf.yml:/src/conf.yml modbus-proxy -c /src/conf.yml
Unable to find image 'modbus-proxy:latest' locally
docker: Error response from daemon: pull access denied for modbus-proxy, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.`

any help here? tia

**Comment by tiagocoutinho** [comment]
I've just created [modbus-proxy-py](https://hub.docker.com/repository/docker/tiagocoutinho/modbus-proxy-py)

so now you have 2 options:

## Build docker locally

This is used mainly in development

```
$ docker build .
$ docker run -p 5020:502 -v $PWD/conf.yml:/src/conf.yml modbus-proxy -c /src/conf.yml
```

## Pull the pre-built image from docker hub

```
$ docker pull tiagocoutinho/modbus-proxy-py
$ docker run -p 5020:502 -v $PWD/conf.yml:/src/conf.yml tiagocoutinho/modbus-proxy-py -c /src/conf.yml
```
